### PR TITLE
add version file for cli

### PR DESCRIPTION
**Pull request by t-oki**
The version of the CLI tool is always 1.0.0 even if you install as 
`go install github.com/rubenv/sql-migrate/...@v1.1.1` and it's quite confusing.
This PR will sync the version of the CLI tool with the git tag.

### CODE REVIEW

**Comment by rubenv** [comment]
That's a file we manually have to maintain?

Can't we use buildinfo for that? https://pkg.go.dev/debug/buildinfo

**Comment by rubenv** [comment]
Though keep in mind that I don't want to drop pre-1.18 support yet.

**Comment by t-oki** [comment]
@rubenv 
Thanks, I used runtime/debug that have support for older go versions.
And I thought it would be better to show version 'dev' when runtime/debug failed to get the version than showing the wrong version

**Comment by rubenv** [comment]
Cool, thanks!

**Pull request merged**
