### PR TITLE
Add custom TxError to add clarity to tx-related error messages.

### PR DESCRIPTION
**Pull request by daved**
This PR will improve the clarity of transaction-related errors by associating messages with a particular migration id.  No additional tests have been added at this time.

For example, this:

    ERROR: syntax error at or near "blah" (SQLSTATE 42601)

will now produce:

    ERROR: syntax error at or near "blah" (SQLSTATE 42601) handling 0000_some_filename.sql

go test passes, but I will need direction from @rubenv regarding whether or not additional testing is desirable and, if so, what is the preference for the design/approach of such testing.

### CODE REVIEW

**Comment by rubenv** [comment]
I like this, but it's probably a bit verbose.

How about adding a `newTxError(migration, err)` function:

```go
func newTxError(migration *PlannedMigration, err error) error {
    return &TxError{
        Migration: migration.Migration,
        Err:       err,
    }
}
```

This would allow you to replace all these blocks:

```go
			err := &TxError{
 				Migration: migration.Migration,
 				Err:       err,
 			}
 
  			return applied, err
```

By this:

```go
return applied, newTxError(migration, err)
```

Which keeps the code much more compact, less duplicated and more readable.

**Comment by daved** [comment]
Thanks for the correction;  This is done.

**Comment by rubenv** [comment]
Ok, looking good for me. Merging!

Probably also need to backport this to https://github.com/rubenv/modl-migrate

**Comment by rubenv** [comment]
Oh and thanks a lot, always a joy to land excellent pull requests!

**Pull request merged**
