### PR TITLE
Update integration tests

### PR DESCRIPTION
**Pull request by nicklaw5**
- Dropped MySQL flag test (If there's a better solution than dropping this, I'm all ears.)
- Run MySQL ENV test
- Updated Travis to test more Go versions

### CODE REVIEW

**Comment by rubenv** [comment]
What's wrong with the flag test?

**Comment by nicklaw5** [comment]
I'm not entirely sure. The [`grep`](https://github.com/rubenv/sql-migrate/blob/master/test-integration/mysql-flag.sh#L10) seems to not pick up the `stdout`. I ended up tweaking it a bit in the end I couldn't get it to pass.

**Comment by rubenv** [comment]
As a result of adding the new Go versions?

It has always worked, so there must be something going on here.

**Comment by rubenv** [comment]
Found it:

```
$ sql-migrate status -config=test-integration/dbconfig.yml -env mysql_noflag
dial tcp 127.0.0.1:3306: getsockopt: connection refused
```

So the config is wrong. Trying a fix.

**Comment by rubenv** [comment]
On Travis: 

```
Error 1045: Access denied for user ''@'localhost' (using password: NO)
```

How did this work before?

**Comment by rubenv** [comment]
Ugh, ignore that last comment.

**Comment by nicklaw5** [comment]
From my testing, it wasn't working from Go v1.6+. I just assumed you left testing v1.5 and below because you were aware of the issue, as I saw that you bumped it to v1.6 once but then bumped it back after the tests failed. [see here](https://github.com/rubenv/sql-migrate/commit/6f4757563362064790a6687a6b60f182062c8634)

**Comment by rubenv** [comment]
Yeah, I remember now, didn't have time to look into it then.

Turns out it gives this:
```
sql: Scan error on column index 0: unsupported Scan, storing driver.Value type []uint8 into type *time.Time
```

As a general rule I don't remove tests unless there's a very good reason to do so (they're there to prevent regressions).

This one shouldn't be removed, we should fix it (otherwise users will get a very cryptic error message).

Question is mainly: why do we connect to the DB before checking the presence of that flag?

**Comment by nicklaw5** [comment]
[This seems related](https://github.com/go-sql-driver/mysql/issues/436)

**Comment by rubenv** [comment]
Just added this to work around it: https://github.com/rubenv/sql-migrate/commit/f5b76a4acc3bb13f1e61a7721dd9cb4b6cc54304

**Comment by nicklaw5** [comment]
Sweet, I'll adjust my PR.

**Comment by rubenv** [comment]
No worries, I cherry-picked the other two.

It's merge, thanks a lot!

**Pull request closed without merging**
