### PR TITLE
Log applied migration id

### PR DESCRIPTION
**Pull request by TamalSaha**

### CODE REVIEW

**Comment by rubenv** [comment]
I won't merge this: sql-migrate can be used as a library, where log output may not be desired.

**Comment by TamalSaha** [comment]
@rubenv, understood. We are using this as a lib. Having no logging was causing us to wonder when things failed. May there can be verbose option with default false to preserve current behavior.

**Comment by rubenv** [comment]
@TamalSaha What went wrong should be present in the error returned by `Exec()`, no?

**Comment by TamalSaha** [comment]
In our case, nothing went wrong, but it was also doing nothing. Sort of got stuck. We don't know what happened yet.

**Pull request closed without merging**
