### PR TITLE
Add detailed MySQL example

### PR DESCRIPTION
**Pull request by muya**
- Add MySQL example with configurations for host, username, password, port & database name on TCP connection

Contributes to #108

### CODE REVIEW

**Comment by rubenv** [comment]
Seems to break CI though! We'll probably have to adjust the credentials.

Could you have a further look at this?

**Comment by muya** [comment]
@rubenv Yep yep! Looking at it

**Comment by muya** [comment]
@rubenv Tests are okay now 🙌🏽

**Comment by rubenv** [comment]
Perfect, thanks a lot!

**Pull request merged**
